apiVersion: apps.open-cluster-management.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
repo:
  chartName: nginx-ingress
  source:
    helmRepo:
      urls:
      - https://github.com/mikeshng/helm-example/raw/gh-pages/nginx-ingress-1.29.0.tgz
    type: helmrepo
  version: 1.29.0
spec:
  defaultBackend:
    replicaCount: 2

