{{ include "parent-chart.deploymenttemplate" . }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.imageName }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http